config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'home#landing'

  get     '/home',      to: 'home#show',      as: :home
  get     '/settings',  to: 'users#settings', as: :user_settings
  delete  '/account',   to: 'users#destroy',  as: :user_account

  resources :challenges do
    collection do
      get :new_from_segment
      get :search_segments
    end

    member do
      put :join
    end
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  include EventSourceable

  MAX_NUMBER_OF_USERS = 5

  class ChallengeAlreadyFullException < Exception; end

  belongs_to :user
  has_many   :user_challenges,    dependent: :destroy
  has_many   :users,              through: :user_challenges, source: :user
  has_many   :subjected_activity, as: :subject, class_name: 'Activity', dependent: :destroy
  has_many   :performed_activity, as: :originator, class_name: 'Activity', dependent: :destroy

  validates :user,         presence: true
  validates :name,         presence: true
  validates :segment_id,   presence: true
  validates :segment_name, presence: true
  validates :end_time,     presence: true

  def add user
    unless user.is_a? User
      raise TypeError.new('user must be a User object')
    end

    transaction do
      if user_challenges.count >= MAX_NUMBER_OF_USERS
        raise ChallengeAlreadyFullException.new
      end

      user_challenges.create user: user
    end
  end

  def end_time_formatted
    return '' unless end_time.is_a?(Time)
    end_time.strftime '%d/%m/%Y %H:%S %p'
  end

  def end_time_timestamp
    end_time ? end_time.to_f * 1000 : 0
  end

  def calculated!
    update_attribute :calculated, true
  end

  def winner
    users.where('user_challenges.moving_time IS NOT NULL').order('user_challenges.moving_time ASC').first
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_strava_user!, only: :show

  def new
    attrs = {
      segment_id: params[:sid],
      segment_name: params[:sname],
      segment_polyline: params[:spl],
      segment_start_latlng: params[:ssll],
      segment_end_latlng: params[:sell]
    }

    event_action = attrs[:segment_id].present? ? :new_step_2 : :new_step_1
    track_event category: :challenge, action: event_action, now: true

    @challenge = current_user.challenges.build attrs
  end

  def new_from_segment
    if params[:sid].blank?
      redirect_to new_challenge_path
      return
    end

    client = current_user.strava_client
    segment = client.segment params[:sid]

    redirect_to new_challenge_path({
      sid: segment.id,
      sname: segment.name,
      spl: segment.map.try(:polyline),
      ssll: segment.start_latlng.join(','),
      sell: segment.end_latlng.join(',')
    })
  rescue MiniStrava::Client::ResourceNotFound
    redirect_to new_challenge_path
  end

  def create
    attrs = challenge_params.to_h
    attrs[:end_time] = Time.at attrs[:end_time].to_i
    @challenge = current_user.owned_challenges.build attrs
    if @challenge.save
      @challenge.users << current_user
      CalculateLeaderboardJob.set(wait_until: @challenge.end_time).perform_later @challenge
      flash_message :success, 'Challenge created successfully. Ask your friends to join!'
      track_event category: :challenge, action: :create, label: @challenge.id
      redirect_to challenge_path(@challenge)
    else
      render :new
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
    order = if @challenge.calculated?
      'user_challenges.moving_time ASC NULLS LAST'
    else
      'user_challenges.created_at ASC'
    end
    @user_challenges = @challenge.user_challenges.includes(:user).order(order)
  end

  def search_segments
    client = current_user.strava_client
    bounds = params[:bounds].to_s.split ','
    if valid_bounds? bounds
      @segments = client.search_segments bounds
    else
      @segments = []
    end

    render layout: false
  end

  def join
    challenge = Challenge.find params[:id]
    current_user.join challenge
    flash_message :success, 'You joined this challenge'
    track_event category: :challenge, action: :join, label: challenge.id, value: 1
  rescue Challenge::ChallengeAlreadyFullException
    flash_message :warning, 'Challenge is already full'
  ensure
    redirect_to challenge_path(challenge)
  end

  private

  def valid_bounds? bounds
    bounds.to_a.size == 4 && bounds.to_a.find{|i| i.blank?}.nil?
  end

  def challenge_params
    params.require(:challenge).permit([
      :segment_id,
      :segment_name,
      :segment_polyline,
      :segment_start_latlng,
      :segment_end_latlng,
      :name,
      :end_time,
    ])
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
  def formatted_moving_time total_seconds
    total_seconds = total_seconds.to_i
    return '--:--:--' if total_seconds < 1

    seconds = total_seconds % 60
    minutes = (total_seconds / 60) % 60
    hours = total_seconds / (60 * 60)

    format '%02d:%02d:%02d', hours, minutes, seconds
  end
end

app/views/challenges/steps/_form.html.erb
<div class="step step-segment">
  <div class="col-xs-12">
    <%= form_for :challenge, url: challenges_path do |f| %>
      <% if @challenge.errors.any? -%>
        <div id="error_explanation">
          <h2><%= pluralize(@challenge.errors.count, 'error') %> prohibited this challenge from being saved:</h2>
          <ul>
            <% @challenge.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end -%>

      <%= f.hidden_field :segment_id %>
      <%= f.hidden_field :segment_name %>
      <%= f.hidden_field :segment_polyline %>
      <%= f.hidden_field :segment_start_latlng %>
      <%= f.hidden_field :segment_end_latlng %>

      <div class="form-group">
        <%= f.label :name, 'Give a name to this challenge' %>
        <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Name...', required: true %>
      </div>

      <div class="form-group" data-widget="date-picker">
        <%= label_tag :end_time_tmp, 'Set an ending date for this challenge' %>
        <%= text_field_tag :end_time_tmp, '', class: 'form-control input-lg date-picker-field', required: true %>
        <%= f.hidden_field :end_time, class: 'timestamp-field' %>
      </div>


      <%= f.submit 'Create', class: 'btn btn-primary btn-lg', data: { disable_with: 'Creating...'}%>

    <% end -%>
  </div>
</div>

app/views/challenges/steps/_segment.html.erb
<div class="step step-segment" data-widget="new-challenge-map" data-widget-search-url="<%= search_segments_challenges_path %>">
  <div class="col-xs-12 col-md-8">
    <div class="map-container">
      <div class="map-content">
        <div id="map"></div>
        <input id="map-search" type="text" placeholder="Search for your segment city/address...">
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-4">
    <h3 class="sidebar-title">Segments</h3>
    <div class="results-loading"></div>
    <div class="results-container"></div>
  </div>
</div>