config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'home#landing'

  get     '/home',      to: 'home#show',      as: :home
  get     '/settings',  to: 'users#settings', as: :user_settings
  delete  '/account',   to: 'users#destroy',  as: :user_account

  resources :challenges do
    collection do
      get :new_from_segment
      get :search_segments
    end

    member do
      put :join
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_strava_user!, only: :landing

  def landing
    if current_user
      redirect_to  home_path
    end
  end

  def show
    @challenges = current_user.challenges.includes(:user)
    @activities = current_user.inbound_activities.page(params[:page]).
                    per(30).order('event_created_at DESC').includes(:originator, :subject)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/landing.html.erb
<div class="sections">
  <section id="home" class="welcome text-center">
    <h2 class="title">Challenge your friends with a segment TimeTrial</h2>
    <a href="<%= user_omniauth_authorize_path(provider: :strava) %>">
      <img src="<%= image_path 'btn-login-strava-2x.png' %>" />
    </a>
  </section>

  <section id="about" class="about text-center">
    <p class="text">Select a segment you love, invite people, ride or run it!</p>
    <a href="#" class="more btn btn-primary" data-toggle="modal" data-target="#modal-about">Learn more</a>
  </section>

  <section id="privacy" class="privacy text-center">
    <p class="text">The access to your Strava account will only be used to retrieve the performance data on the challenge segment.</p>
    <a href="#" class="more btn btn-primary" data-toggle="modal" data-target="#modal-privacy">Learn more</a>
  </section>
</div>

<%= render partial: 'home/modals/about' %>
<%= render partial: 'home/modals/privacy' %>

app/views/home/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <h2>Activities</h2>

      <ul class="items">
        <% if @activities.any? -%>
          <% @activities.each do |activity| -%>
            <li class="item">
            <div class="clearfix">
              <%= render partial: "home/activities/#{activity.action}", locals: { activity: activity } %>
            </div>
            <hr />
            </li>
          <% end %>
        <% else %>
          <p>No activities yet. <%= link_to 'Start a new challenge and invite your friends', new_challenge_path %></p>
        <% end %>
      </ul>

      <%= paginate @activities %>
    </div>

    <div class="col-xs-12 col-md-4">
      <h2>Challenges</h2>

      <ul class="items">
        <% if @challenges.any? -%>
          <% @challenges.each do |challenge| -%>
            <li class="item">
            <div class="clearfix">
              <div class="left">
                <img src="<%= challenge.user.profile_picture_url  %>" class="avatar" />
              </div>
              <div class="right">
                <span class="date">
                  ending on <strong><%= l challenge.end_time, format: :short %></strong>
                </span>
                <p class="description">
                <span class="challenge"><%= link_to challenge.name, challenge_path(challenge)%></span>
                </p>
              </div>
            </div>
            <hr />
            </li>
          <% end %>
        <% else %>
          <p>No challenges yet. <%= link_to 'Start a new challenge and invite your friends', new_challenge_path %></p>
        <% end %>
      </ul>
    </div>
  </div>
</div>