config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'home#landing'

  get     '/home',      to: 'home#show',      as: :home
  get     '/settings',  to: 'users#settings', as: :user_settings
  delete  '/account',   to: 'users#destroy',  as: :user_account

  resources :challenges do
    collection do
      get :new_from_segment
      get :search_segments
    end

    member do
      put :join
    end
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  include EventSourceable

  MAX_NUMBER_OF_USERS = 5

  class ChallengeAlreadyFullException < Exception; end

  belongs_to :user
  has_many   :user_challenges,    dependent: :destroy
  has_many   :users,              through: :user_challenges, source: :user
  has_many   :subjected_activity, as: :subject, class_name: 'Activity', dependent: :destroy
  has_many   :performed_activity, as: :originator, class_name: 'Activity', dependent: :destroy

  validates :user,         presence: true
  validates :name,         presence: true
  validates :segment_id,   presence: true
  validates :segment_name, presence: true
  validates :end_time,     presence: true

  def add user
    unless user.is_a? User
      raise TypeError.new('user must be a User object')
    end

    transaction do
      if user_challenges.count >= MAX_NUMBER_OF_USERS
        raise ChallengeAlreadyFullException.new
      end

      user_challenges.create user: user
    end
  end

  def end_time_formatted
    return '' unless end_time.is_a?(Time)
    end_time.strftime '%d/%m/%Y %H:%S %p'
  end

  def end_time_timestamp
    end_time ? end_time.to_f * 1000 : 0
  end

  def calculated!
    update_attribute :calculated, true
  end

  def winner
    users.where('user_challenges.moving_time IS NOT NULL').order('user_challenges.moving_time ASC').first
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_strava_user!, only: :show

  def new
    attrs = {
      segment_id: params[:sid],
      segment_name: params[:sname],
      segment_polyline: params[:spl],
      segment_start_latlng: params[:ssll],
      segment_end_latlng: params[:sell]
    }

    event_action = attrs[:segment_id].present? ? :new_step_2 : :new_step_1
    track_event category: :challenge, action: event_action, now: true

    @challenge = current_user.challenges.build attrs
  end

  def new_from_segment
    if params[:sid].blank?
      redirect_to new_challenge_path
      return
    end

    client = current_user.strava_client
    segment = client.segment params[:sid]

    redirect_to new_challenge_path({
      sid: segment.id,
      sname: segment.name,
      spl: segment.map.try(:polyline),
      ssll: segment.start_latlng.join(','),
      sell: segment.end_latlng.join(',')
    })
  rescue MiniStrava::Client::ResourceNotFound
    redirect_to new_challenge_path
  end

  def create
    attrs = challenge_params.to_h
    attrs[:end_time] = Time.at attrs[:end_time].to_i
    @challenge = current_user.owned_challenges.build attrs
    if @challenge.save
      @challenge.users << current_user
      CalculateLeaderboardJob.set(wait_until: @challenge.end_time).perform_later @challenge
      flash_message :success, 'Challenge created successfully. Ask your friends to join!'
      track_event category: :challenge, action: :create, label: @challenge.id
      redirect_to challenge_path(@challenge)
    else
      render :new
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
    order = if @challenge.calculated?
      'user_challenges.moving_time ASC NULLS LAST'
    else
      'user_challenges.created_at ASC'
    end
    @user_challenges = @challenge.user_challenges.includes(:user).order(order)
  end

  def search_segments
    client = current_user.strava_client
    bounds = params[:bounds].to_s.split ','
    if valid_bounds? bounds
      @segments = client.search_segments bounds
    else
      @segments = []
    end

    render layout: false
  end

  def join
    challenge = Challenge.find params[:id]
    current_user.join challenge
    flash_message :success, 'You joined this challenge'
    track_event category: :challenge, action: :join, label: challenge.id, value: 1
  rescue Challenge::ChallengeAlreadyFullException
    flash_message :warning, 'Challenge is already full'
  ensure
    redirect_to challenge_path(challenge)
  end

  private

  def valid_bounds? bounds
    bounds.to_a.size == 4 && bounds.to_a.find{|i| i.blank?}.nil?
  end

  def challenge_params
    params.require(:challenge).permit([
      :segment_id,
      :segment_name,
      :segment_polyline,
      :segment_start_latlng,
      :segment_end_latlng,
      :name,
      :end_time,
    ])
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
  def formatted_moving_time total_seconds
    total_seconds = total_seconds.to_i
    return '--:--:--' if total_seconds < 1

    seconds = total_seconds % 60
    minutes = (total_seconds / 60) % 60
    hours = total_seconds / (60 * 60)

    format '%02d:%02d:%02d', hours, minutes, seconds
  end
end

app/views/challenges/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Challenge - Select a segment</h1>
    </div>

    <% if @challenge.segment_id.nil? -%>
      <%= render partial: 'challenges/steps/segment' %>
    <% else -%>
      <%= render partial: 'challenges/steps/form' %>
    <% end %>
  </div>
</div>

app/views/challenges/search_segments.html.erb
<div class="container">
  <% if @segments.any? -%>
    <ul class="items">
      <% @segments.each do |segment| %>
        <li class="item">
        <strong class="name"><%= segment.name %></strong>
        <span class="distance"><%= segment.distance %>m</span>
        <a href="<%= new_from_segment_challenges_path sid: segment.id %>" class="btn btn-primary btn-sma">Use this segment</a>
        <hr />
        </li>
      <% end -%>
    </ul>
  <% else -%>
    <p>No results</p>
  <% end -%>
</div>

app/views/challenges/show.html.erb
<div class="container">
  <div class="challenge-header" data-widget="countdown" data-widget-time="<%= @challenge.end_time %>">
    <% if @challenge.calculated? -%>
      <p>
      This challenge is over.
      <% if user = @challenge.winner %>
        The winner is <strong><%= user.name %></strong>
      <% end %>
      </p>
    <% else %>
      <div data-widget="countdown" data-widget-time="<%= @challenge.end_time %>">
        <h3 class="countdown"></h3>
        <p class="waiting">This challenge is already over but the leaderboard has not been generated yet. Come back later to see who won!</p>
      </div>
    <% end -%>
  </div>

  <div class="col-xs-12">
    <h1><%= @challenge.name %></h1>
  </div>

  <div class="step step-segment" data-widget="challenge-map-detail" data-widget-polyline="<%= @challenge.segment_polyline %>" data-widget-start_latlng="<%= @challenge.segment_start_latlng %>" data-widget-end_latlng="<%= @challenge.segment_end_latlng %>">
    <div class="col-xs-12 col-md-8">
      <div class="share-box">
        <p class="text">Invite someone to this challenge by sharing this link:</p>
        <input type="text" class="url" value="<%= challenge_url @challenge %>" />
      </div>
      <div class="map-container">
        <div class="map-content">
          <div id="map"></div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <h3 class="sidebar-title"><%= @challenge.segment_name %></h3>

      <ul class="members">
        <% @user_challenges.each_with_index do |uc, index| -%>
          <li class="user">
          <img src="<%= uc.user.profile_picture_url %>" class="avatar pull-left" />
          <span class="name">
            <% if @challenge.calculated? -%>
              <span class="position">
                <%= index + 1 %>&ordm;
              </span> -
            <% end -%>
            <%= uc.user.name %>
          </span>
          <span class="time">Time: <%= formatted_moving_time uc.moving_time %> </span>
          <hr />
          </li>
        <% end %>
      </ul>

      <% if !@challenge.calculated? && (!current_user || !current_user.joined(@challenge)) %>
        <p>
        <%= link_to 'Join Challenge', join_challenge_path(@challenge, return_to: challenge_path(@challenge)), method: :put, class: 'btn btn-primary btn-lg' %>
        </p>
      <% end -%>

      <a href="https://www.strava.com/segments/<%= @challenge.segment_id %>" target="_blank">
        <small>Check this segment on Strava</small>
      </a>
    </div>
  </div>
</div>