config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'home#landing'

  get     '/home',      to: 'home#show',      as: :home
  get     '/settings',  to: 'users#settings', as: :user_settings
  delete  '/account',   to: 'users#destroy',  as: :user_account

  resources :challenges do
    collection do
      get :new_from_segment
      get :search_segments
    end

    member do
      put :join
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetrial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-zfNOIwZr3WSIi0jlCp7OTmfMz86gUQ4&libraries=places,geometry">
    </script>
    <% if Rails.env.production? -%>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-129369-27', 'auto');
      </script>
    <% end -%>

    <link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>">
  </head>

  <%= content_tag :body, class: body_class_name, data: body_data do %>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">
            <img src="<%= asset_path 'logo.png' %>" alt="TimeTrial"/>
          </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right" data-widget="slide-links">
            <% if current_user %>
              <li>
                <p class="navbar-btn">
                  <%= link_to 'New Challenge', new_challenge_path, class: 'btn btn-primary' %>
                </p>
              </li>
              <li>
                <%= link_to current_user.name.presence || 'Anonymous', home_path %>
              </li>
              <li>
                <%= link_to 'Settings', user_settings_path %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path %>
              </li>
            <% else %>
              <li>
                <a href="<%= root_path %>#home" class="slide-link">Home</a>
              </li>
              <li>
                <a href="<%= root_path %>#about" class="slide-link">How it works</a>
              </li>
              <li>
                <a href="<%= root_path %>#privacy" class="slide-link">Privacy</a>
              </li>
            <% end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

      <% each_flash_message do |k, v| -%>
        <div class="m-x-auto alert alert-dismissible alert-<%= flash_to_bootstrap k %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
          <%= v %>
        </div>
      <% end -%>

    <%= yield %>

    <footer>
      &copy; <%= Time.now.year %> <a href="http://gravityblast.com">Andrea Franz</a> |
      <a href="https://twitter.com/gravityblast">@gravityblast</a>
    </footer>
  <% end -%>
</html>